var character = q('character'); // unused...
var char = q('char'); // 'default','frisk','chara','asriel','monster'
var gender = q('gender'); // 'default','none','male','female','thing','other','non'
var soulcolor = q('soulcolor'); // (css color)
var soultype = q('soultype'); // 'default','none','human','monster','pacman'
var haircolor = q('haircolor'); // (css color)
var hairstyle = q('hairstyle'); // 'default','none','short','long','spiked','bun','ponytail','pigtails','cap','tophat'
var eyecolor = q('eyecolor'); // (css color)
var shirtcolor = q('shirtcolor'); // (css color)
var shirtcolor2 = q('shirtcolor2'); // (css color)
var shirtstyle = q('shirtstyle'); // 'default','long','short','dress','mtt'
var pantscolor = q('pantscolor'); // (css color)
var pantsstyle = q('pantsstyle'); // 'default','long','short','skirt'
var shoecolor = q('shoecolor'); // (css color)
var shoestyle = q('shoestyle'); // 'default','plain','boots','heels','cowboy'
var headpc = q('headpc'); // 'none','cap','tophat','crown','mtt'
var headpccolor = q('headpccolor'); // (css color)
var headpccolor2 = q('headpccolor2'); // (css color)
var torsopc = q('torsopc'); // 'none','cape','swords'
var torsopccolor = q('torsopccolor'); // (css color)
var torsopccolor2 = q('torsopccolor2'); // (css color)
var legpc = q('legpc'); // 'none','kneepad'
var legpccolor = q('legpccolor'); // (css color)
var legpccolor2 = q('legpccolor2'); // (css color)
